"""Install new source photography and rebuild the WebP ladders.

Usage:
    python tools/import_photos.py <source-folder> [--min 1600]

Maps source files onto site photo stems by filename, refuses anything too small
to be an honest improvement, then hands off to build_assets so the ladder is
generated by the same code the site is tested against.
"""
import argparse
import shutil
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"

# Source filename stem (case-insensitive) -> the site stem it replaces.
STEMS = {
    "hero": "tech-hvac",
    "tech-hvac": "tech-hvac",
    "hvac": "tech-hvac",
    "aircon": "tech-hvac",
    "tech-electrical": "tech-electrical",
    "electrical": "electrical",
    "switchboard": "electrical",
    "construction": "construction",
    "fitout": "construction",
}

# Below this the import is not an upgrade on what already ships, and the ladder
# would be capped right back where it is now.
MIN_WIDTH = 1600


def install(source: Path, min_width: int, dest: Path = None) -> list[str]:
    dest = ASSETS if dest is None else dest
    touched = []
    for f in sorted(source.iterdir()):
        if f.suffix.lower() not in (".jpg", ".jpeg", ".png", ".webp"):
            continue
        stem = STEMS.get(f.stem.lower())
        if stem is None:
            print(f"skip   {f.name}: no mapping, add one to STEMS")
            continue
        with Image.open(f) as im:
            width, height = im.size
            if width < min_width:
                print(f"REFUSE {f.name}: {width}px wide, minimum is {min_width}px")
                continue
            im.convert("RGB").save(dest / f"{stem}.jpg", "JPEG", quality=92, subsampling=0)
        print(f"install {f.name} -> {stem}.jpg  {width}x{height}")
        touched.append(stem)
    return touched


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("source", type=Path)
    ap.add_argument("--min", type=int, default=MIN_WIDTH)
    args = ap.parse_args()
    if not args.source.is_dir():
        print("not a folder:", args.source)
        return 2
    touched = install(args.source, args.min)
    if not touched:
        print("nothing installed")
        return 1
    sys.path.insert(0, str(ROOT / "tools"))
    import build_assets
    build_assets.rebuild_photos()
    print("\nnow run: python tools/build_pages.py && python -m pytest tests/ -q")
    return 0


def demo() -> None:
    """Self-check: the size floor is what stops another silent upscale."""
    import tempfile
    with tempfile.TemporaryDirectory() as d:
        src = Path(d) / "in"
        out = Path(d) / "out"
        src.mkdir()
        out.mkdir()
        Image.new("RGB", (800, 1000), "grey").save(src / "hvac.jpg")
        assert install(src, 1600, out) == [], "a 800px source must be refused"
        Image.new("RGB", (2400, 3000), "grey").save(src / "hvac.jpg")
        assert install(src, 1600, out) == ["tech-hvac"], "a 2400px source must install"
        assert (out / "tech-hvac.jpg").exists()
    print("demo ok")


if __name__ == "__main__":
    if "--demo" in sys.argv:
        demo()
    else:
        raise SystemExit(main())
